### ISSUE TITLE
using MainCharacter_Basil_Dark instead of MainCharacter_Basil_dark

### ISSUE THREAD

**Issue by bobatealee** [goaaats/OmoriDialogue#1]
This file seems to be case sensitive, and you're using an uppercase D instead of a lowercase d. This causes some Basil portraits to not render correctly.

**Comment by goaaats** [comment]
Hmm, these are straight from the game files - I assume it wasn't a problem on Windows since it's not case sensitive, wonder if that caused problems for them on OS X.

I'll make a copy with the fixed name, thanks for bringing it up.
